version: "3"
services:
  upload-file-frontend:
    build:
      context: ./upload-file-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./upload-file-frontend:/usr/src/app
    depends_on:
      - upload-file-backend

  upload-file-backend:
    build:
      context: ./upload-file-backend
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    volumes:
      - ./upload-file-backend:/usr/src/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=test

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: