# Use Node.js 22 as the base image
FROM node:22-alpine

# Set the working directory in the Docker container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the application files to the working directory
COPY . .

# Compile the TypeScript files to JavaScript
RUN npm run build

# Expose port 8080 for the application
EXPOSE 8080

# Start the application
CMD [ "node", "dist/main" ]